module.exports = {
  SESSION_ID: "SUBZERO-MD;;;aUdRUbbR#pRFLKFvKY35-uLl3MXwM_owVCgAkCXE50iQBGIH55Gs", // PUT SESSION ID HERE 
  OWNER_NUMBER: "263719647303", // PUT OWNER NUMBER HERE
  PREFIX: "." // DEFAULT PREFIX
};
